### PR TITLE
Update the ics-generator

### PR DESCRIPTION
**Pull request by MrJack91**
Thanks you for your work!

Have made some usefull changes:
fix: working allday support
add: add static timezone support
add: customize filename support
add: last modified date
rename: all get/setter like the ics properties
rm: remove status property
rm: unnecessary alias methods -> clean up
improve: date handling -> clean up

### CODE REVIEW

**Comment by hising** [comment]
Cool, I will verify the fixes and merge it if everything looks ok

**Comment by MrJack91** [comment]
Are you still alive? ;)

**Comment by hising** [comment]
Yeah, I have not had the possibility to test this yet.

**Comment by MrJack91** [comment]
great. thanks

**Pull request merged**
